---
- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  tasks:
    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: /home/ubuntu/genre_clf
        state: directory

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/ubuntu/genre_clf/{{ item | basename }}"
      with_items:
        - /home/ubuntu/genre_clf/server/requirements.txt
        - /home/ubuntu/genre_clf/server/app.py
        - /home/ubuntu/genre_clf/server/utils/feature_extraction.py
        - /home/ubuntu/genre_clf/server/model/min_max_scaler.pkl
        - /home/ubuntu/genre_clf/server/model/xgb_mgen.pkl
        - /home/ubuntu/genre_clf/server/templates/index.html
        - /home/ubuntu/genre_clf/server/templates/result.html

    - name: Install python
      ansible.builtin.shell: "sudo apt install --yes --force-yes python3-pip"

    - name: Install all requirements
      ansible.builtin.shell: "pip install -r /home/ubuntu/genre_clf/requirements.txt"

    - name: Install gunicorn
      ansible.builtin.shell: "sudo pip install gunicorn"

    - name: Run the application using gunicorn
      ansible.builtin.shell: "gunicorn --bind 0.0.0.0:5000 app:app"
      args:
        chdir: /home/ubuntu/genre_clf/server
        creates: /home/ubuntu/genre_clf/server/gunicorn.pid
