---
- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  vars:
    remote_dir: "/home/ubuntu/genre_clf"
    local_files:
      - "server/requirements.txt"
      - "server/app.py"
      - "server/utils/feature_extraction.py"
      - "server/model/min_max_scaler.pkl"
      - "server/model/xgb_mgen.pkl"
      - "server/templates/index.html"
      - "server/templates/result.html"
  tasks:

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_dir }}/"
      loop: "{{ local_files }}"

    - name: Update package lists
      ansible.builtin.shell: 
        cmd: sudo apt update

    - name: Install python3-pip
      ansible.builtin.shell: 
        cmd: sudo apt install --yes --force-yes python3-pip

    - name: Install all requirements
      ansible.builtin.shell: 
        cmd: pip3 install -r /home/ubuntu/genre_clf/requirements.txt

    - name: Ensure the firewall allows port 5000 (Flask default)
      ansible.builtin.ufw:
        rule: allow
        name: '5000'
        state: enabled

    - name: Start python server asynchronously
      ansible.builtin.shell:
        cmd: "python3 /home/ubuntu/genre_clf/app.py"
      async: 3600  # Maximum running time (1 hour)
      poll: 1      # Wait for completion to ensure server starts
      register: python_output

    - name: Print the website link
      ansible.builtin.debug:
        msg: "You can access the application at: http://{{ ansible_host }}:5000/"

