---
- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  vars:
    remote_dir: "/home/ubuntu/genre_clf"
    local_files:
      - "/home/ubuntu/jenkins/workspace/semenistyh_build/server/requirements.txt"
      - "/home/ubuntu/jenkins/workspace/semenistyh_build/server/app.py"
      - "/home/ubuntu/jenkins/workspace/semenistyh_build/server/utils/feature_extraction.py"
      - "/home/ubuntu/jenkins/workspace/semenistyh_build/server/model/min_max_scaler.pkl"
      - "/home/ubuntu/jenkins/workspace/semenistyh_build/server/model/xgb_mgen.pkl"
      - "/home/ubuntu/jenkins/workspace/semenistyh_build/server/templates/index.html"
      - "/home/ubuntu/jenkins/workspace/semenistyh_build/server/templates/result.html"
  tasks:

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Check if files exist
      ansible.builtin.stat:
        path: "{{ item }}"
      loop: "{{ local_files }}"
      register: file_check

    - name: Fail if any file is missing
      ansible.builtin.fail:
        msg: "File {{ item.stat.path }} is missing."
      when: not item.stat.exists
      loop: "{{ file_check.results }}"

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_dir }}/"
        remote_src: no
      loop: "{{ local_files }}"

    - name: Update
      ansible.builtin.shell:
        cmd: sudo apt update

    - name: Install python
      ansible.builtin.shell:
        cmd: sudo apt install --yes python3-pip

    - name: Install all requirements
      ansible.builtin.shell:
        cmd: pip install -r {{ remote_dir }}/requirements.txt

    - name: Start python file
      ansible.builtin.shell:
        cmd: python3 {{ remote_dir }}/app.py
