---
- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  vars:
    remote_dir: "/home/ubuntu/genre_clf"
    local_files:
      - "{{ playbook_dir }}/server/requirements.txt"
      - "{{ playbook_dir }}/server/app.py"
      - "{{ playbook_dir }}/server/utils/feature_extraction.py"
      - "{{ playbook_dir }}/server/model/min_max_scaler.pkl"
      - "{{ playbook_dir }}/server/model/xgb_mgen.pkl"
      - "{{ playbook_dir }}/server/templates/index.html"
      - "{{ playbook_dir }}/server/templates/result.html"
  tasks:

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_dir }}/"
        remote_src: yes  # указываем, что файлы находятся на контроллере
      loop: "{{ local_files }}"

    - name: Update system packages
      ansible.builtin.shell: 
        cmd: sudo apt update

    - name: Install Python3 and pip
      ansible.builtin.shell: 
        cmd: sudo apt install --yes python3-pip

    - name: Install all required Python packages
      ansible.builtin.shell: 
        cmd: pip install -r {{ remote_dir }}/requirements.txt

    - name: Start the Python application
      ansible.builtin.shell: 
        cmd: python3 {{ remote_dir }}/app.py
